services:
  start-helm:
    image: helmstart/helm-start:latest
    container_name: helm-start
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      TZ: "Europe/Berlin"
    ports:
      - "80:80"
