name: Ping Test
description: For integration-testing deployments deployed with helmify helm charts

inputs:
  name:
    description: 'The directory & image name & helm release name'
    required: true
  expect:
    description: 'The expected response from the ping test'
    required: true


runs:
  using: "composite"
  steps:
    - name: Port-Forward ${{inputs.name}}
      run: kubectl port-forward svc/${{inputs.name}} 18080:8080 &
      shell: bash
    - name: Ping ${{inputs.name}}
      run: mvn test -Dtest=KindPingTest -Durl=http://localhost:18080/ping -Dexpected=${{inputs.expect}}
      shell: bash
