spring:
  application:
    name: helm-start
  initializr:
    host: start.spring.io
  devtools:
    restart:
      additional-paths: src/main/resources/static
  threads:
    virtual:
      enabled: true

logging:
  level:
    web: DEBUG

management:
  server:
    port: 9090

