name: CLI dev Build

on:
  push:
    branches: [ "cli-pipeline", "develop", "feature/**", "fix/**" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: cd cli && go get .
      - name: Build CLI - Windows 64bit
        run: cd cli && env GOOS=windows GOARCH=amd64 go build -o dev-helm-start-win64.exe .
      - name: Build CLI - Windows 32bit
        run: cd cli && env GOOS=windows GOARCH=386 go build -o dev-helm-start-win32.exe .
      - name: Build CLI - Linux 64bit
        run: cd cli && env GOOS=linux GOARCH=amd64 go build -o dev-helm-start-linux64 .
      - name: Build CLI - Linux 32bit
        run: cd cli && env GOOS=linux GOARCH=386 go build -o dev-helm-start-linux32 .
      - name: List
        run: cd cli && ls -lah
      - name: Upload Win32 DEV binary
        uses: actions/upload-artifact@v4
        with:
          name: dev-helm-start-win32.exe
          path: cli/dev-helm-start-win32.exe
      - name: Upload Win64 DEV binary
        uses: actions/upload-artifact@v4
        with:
          name: dev-helm-start-win64.exe
          path: cli/dev-helm-start-win64.exe
      - name: Upload Linux32 DEV binary
        uses: actions/upload-artifact@v4
        with:
          name: dev-helm-start-linux32
          path: cli/dev-helm-start-linux32
      - name: Upload Linux64 DEV binary
        uses: actions/upload-artifact@v4
        with:
          name: dev-helm-start-linux64
          path: cli/dev-helm-start-linux64
