name: Helmify E2E Testing

on:
  push:
    branches: [ "test-e2e" ]
  pull_request:
    branches: [ "main" ]

jobs:

  setupCluster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Up Cluster
        uses: ./.github/actions/setup-cluster

  startHelmify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Up Helmify Build Environment
        uses: ./.github/actions/setup-build
      - name: Start Helmify Docker Container
        uses: ./.github/actions/run-helmify

  springE2ePostgres:
    runs-on: ubuntu-latest
    needs: [setupCluster,  startHelmify]
    steps:
      - uses: actions/checkout@v4
      - name: Checkout Helmify E2E Tests
        uses: actions/checkout@v4
        with:
          repository: helmify/testing.git
          ref: main
          path: testing
      - name: Set Up Build Environment
        uses: ./.github/actions/setup-build
      - name: Run Spring Postgres Tester
        uses: ./.github/actions/run-tester
        with:
          name: spring-postgres-tester
          type: spring
          port: 18000
          expect: postgres

  quarkusE2ePostgres:
    runs-on: ubuntu-latest
    needs: [setupCluster,  startHelmify]
    steps:
      - uses: actions/checkout@v4
      - name: Checkout Helmify E2E Tests
        uses: actions/checkout@v4
        with:
          repository: helmify/testing.git
          ref: main
          path: testing
      - name: Set Up Build Environment
        uses: ./.github/actions/setup-build
      - name: Run Quarkus Postgres Tester
        uses: ./.github/actions/run-tester
        with:
          name: quarkus-postgres-tester
          type: quarkus
          port: 18001
          expect: postgres
