name: Helmify E2E Testing

on:
  push:
    branches: [ "feature/82-add-e2e-testing-pipeline-using-test-apps" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Helmify
        uses: actions/checkout@v4
      - name: Checkout Helmify E2E Tests
        uses: actions/checkout@v4
        with:
          repository: helmify/testing.git
          ref: main
          path: testing
      ### Build
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1
      - name: create cluster
        uses: helm/kind-action@v1.8.0
      - name: set context
        run: kubectl config use-context kind-chart-testing
      - name: set context
        run: kubectl config set-cluster chart-testing
      - name: Set up JDK 21
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: 21
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      # This is a separate action that sets up buildx runner
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # So now you can use Actions' own caching!
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build Helmify
        run: mvn -B clean test spring-boot:build-image --file pom.xml -Dspring-boot.build-image.imageName=helmify/helmify
      ### Integration-Testing for generated Helm Charts
      - name: Start helmify
        run: docker run -d -p 8080:8080 -p 9090:9090 helmify/helmify:latest
      - name: Wait for Helmify Start
        run: |
          until printf "." && curl --silent http://localhost:9090/actuator/health; do \
          sleep 2; \
          done;
      - name: Build Spring Postgres Tester
        run: mvn spring-boot:build-image -Dspring-boot.build-image.imageName=spring-postgres-tester:0.1.0 --file testing/spring-postgres-tester/pom.xml
      - name: Generate Spring Postgres Tester Helm Chart
        run: |
          curl -X POST --data @testing/spring-postgres-tester/pom.xml  -o spring-postgres-tester.zip -H "Content-Type: application/json" "http://localhost:8080/api/cli?name=spring-postgres-tester&version=0.1.0"
      - name: Unzip Spring Postgres Tester Helm Chart
        run: unzip spring-postgres-tester.zip -d spring-postgres-tester-chart
      - name: Helm Dependency Update
        run: cd spring-postgres-tester-chart && helm dependency update
      - name: Deploy Spring Postgres Tester
        run: kind load docker-image spring-postgres-tester:0.1.0 --name chart-testing && helm install spring-postgres-tester spring-postgres-tester-chart
      - name: Test Spring Postgres Tester Deployment
        run: mvn test -Dtest=KindClusterTest -Dexpected-deployments=spring-postgres-tester -Dexpected-services=spring-postgres-tester,spring-postgres-tester-postgresql -Dexpected-pods=spring-postgres-tester,spring-postgres-tester-postgresql -Dexpected-configs=spring-postgres-tester-config -Dexpected-secrets=spring-postgres-tester,spring-postgres-tester-postgresql
      - name: Port-Forward Spring Postgres Tester
        run: kubectl port-forward svc/spring-postgres-tester 8080:8080 &
      - name: Ping Spring Postgres Tester
        run: mvn test -Dtest=KindPingTest -Durl=http://localhost:8080/ping -Dexpected=postgres
