name: Helmify E2E Testing

on:
  push:
    branches: ["feature/82-add-e2e-testing-pipeline-using-test-apps"]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: create cluster
        uses: helm/kind-action@v1.8.0
      - name: set context
        run: kubectl config use-context kind-chart-testing
      - name: Deploy Spring Postgres Tester
        run: kind load docker-image busybox:latest
