# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: psalg-dev-patch-1 Build

on:
  push:
    branches: [ "psalg-dev-patch-1" ]
  pull_request:
    branches: [ "psalg-dev-patch-1" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: get-pom-version
      id: pom-version
      uses: PERES-Richard/maven-get-version-action@v3.0.0
    
    - name: Print Maven POM project version
      run: echo "${{ steps.pom-version.outputs.version }}" | sed "s/-SNAPSHOT//"
      
